"""Boot-time federation wiring (Item 16).

Iterates over the loaded extensions, finds every concrete
:class:`AbstractGraphQLProvider` subclass with a configured upstream, runs
the introspect → transform → register → lift pipeline, and merges the
resulting Pydantic models / federated subgraphs with the framework's
existing GraphQL surface.

Two integration points are offered:

* :func:`install_external_federation` — async; runs the full federation
  pipeline. Call from FastAPI's startup event after the model registry has
  committed and BEFORE the Strawberry schema is built.
* :func:`reset_federation_state` — test helper.
"""

from __future__ import annotations

import asyncio
from typing import Any, Dict, Iterable, List, Optional

from serverframework.lib.Federation_GQL import (
    MergedSchemaRegistry,
    global_registry,
    reset_global_registry,
)
from serverframework.lib.Logging import logger


async def install_external_federation(
    *,
    providers: Optional[Iterable[Any]] = None,
    registry: Optional[MergedSchemaRegistry] = None,
    skip_unconfigured: bool = True,
) -> Dict[str, Any]:
    """Run the federation pipeline for every concrete GraphQL provider.

    ``providers`` is the iterable of provider classes to federate. When
    omitted, the function iterates the registered extensions and discovers
    subclasses of :class:`AbstractGraphQLProvider` that declare an
    :attr:`upstream_url`.

    Returns ``{provider_name: lift_result}`` so the caller can route the
    lifted Pydantic models into the model registry. Failures are logged and
    skipped — federation MUST NOT prevent the rest of the framework from
    starting; an unreachable upstream surfaces via :meth:`health_check`.
    """

    from serverframework.extensions.AbstractGraphQLProvider import (
        AbstractGraphQLProvider,
    )

    target_registry = registry or global_registry()
    discovered: List[type] = list(providers or _discover_providers())

    lifted: Dict[str, Any] = {}
    for provider_cls in discovered:
        if not issubclass(provider_cls, AbstractGraphQLProvider):
            continue
        if not getattr(provider_cls, "upstream_url", ""):
            if skip_unconfigured:
                logger.debug(
                    "Skipping %s — no upstream_url configured", provider_cls.__name__
                )
                continue
        try:
            ingested = await provider_cls.register_with_registry(registry=target_registry)
        except Exception as exc:
            logger.warning(
                "Federation pipeline failed for %s: %s", provider_cls.__name__, exc
            )
            continue
        try:
            lift_result = provider_cls.lift_to_pydantic(ingested)
        except Exception as exc:
            logger.warning(
                "SDL→Pydantic lift failed for %s: %s", provider_cls.__name__, exc
            )
            lift_result = None
        lifted[provider_cls.__name__] = lift_result

    # Materialize the merged schema so the listeners (and the routes
    # generated by GQL→REST projection) see the final state.
    target_registry.build()
    return lifted


def install_external_federation_sync(
    *,
    providers: Optional[Iterable[Any]] = None,
    registry: Optional[MergedSchemaRegistry] = None,
) -> Dict[str, Any]:
    """Synchronous wrapper for environments without a running event loop."""

    return asyncio.run(
        install_external_federation(providers=providers, registry=registry)
    )


def _discover_providers() -> List[type]:
    """Walk the extension registry to find configured GraphQL providers."""

    try:
        from serverframework.extensions.AbstractExtensionProvider import (
            ExtensionRegistry,
            AbstractStaticProvider,
        )
        from serverframework.extensions.AbstractGraphQLProvider import (
            AbstractGraphQLProvider,
        )
    except ImportError:
        return []

    found: List[type] = []
    registry_cls = ExtensionRegistry
    extensions = getattr(registry_cls, "extensions", None) or []
    for ext in extensions:
        for prov in getattr(ext, "_providers", []) or []:
            if (
                isinstance(prov, type)
                and issubclass(prov, AbstractGraphQLProvider)
                and prov is not AbstractGraphQLProvider
            ):
                found.append(prov)
    return found


def reset_federation_state() -> None:
    """Test helper: clear the global merged schema registry."""

    reset_global_registry()


__all__ = [
    "install_external_federation",
    "install_external_federation_sync",
    "reset_federation_state",
]
