"""AI request and statistics tables

Revision ID: f8d58b06ec4b
Revises:
Create Date: 2026-08-20 19:59:26.033388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8d58b06ec4b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ('ext_ai',)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_requests",
        sa.Column("name", sa.String(), nullable=True, comment="The name"),
        sa.Column(
            "prompt",
            sa.String(),
            nullable=False,
            comment="The prompt sent to the AI provider",
        ),
        sa.Column(
            "response",
            sa.String(),
            nullable=True,
            comment="The response from the AI provider",
        ),
        sa.Column(
            "model_name", sa.String(), nullable=True, comment="The AI model used"
        ),
        sa.Column(
            "provider_instance_id",
            sa.String(),
            nullable=False,
            comment="Provider instance that handled the request",
        ),
        sa.Column(
            "tokens_used",
            sa.Integer(),
            nullable=True,
            comment="Number of tokens consumed",
        ),
        sa.Column(
            "cost", sa.Float(), nullable=True, comment="Cost of the request"
        ),
        sa.Column(
            "status",
            sa.String(),
            nullable=False,
            comment="Request status: pending, completed, failed",
        ),
        sa.Column(
            "error_message",
            sa.String(),
            nullable=True,
            comment="Error message if request failed",
        ),
        sa.Column(
            "request_type",
            sa.String(),
            nullable=False,
            comment="Type of AI request: text_generation, embedding, image_generation, etc.",
        ),
        sa.Column(
            "created_by_user_id",
            sa.String(),
            nullable=True,
            comment="Optional foreign key to UserModel",
        ),
        sa.Column(
            "updated_by_user_id",
            sa.String(),
            nullable=True,
            comment="Optional foreign key to UserModel",
        ),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_by_user_id", sa.String(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        comment="Tracks AI requests and their associated metadata",
        info={
            "source_module": "extensions.ai.BLL_AI",
            "extension": "ai",
        },
    )
    op.create_table(
        "ai_statistic",
        sa.Column(
            "date",
            sa.DateTime(),
            nullable=False,
            comment="Date for these statistics",
        ),
        sa.Column(
            "provider_name",
            sa.String(),
            nullable=False,
            comment="Name of the AI provider",
        ),
        sa.Column(
            "model_name", sa.String(), nullable=True, comment="Specific model name"
        ),
        sa.Column(
            "request_count",
            sa.Integer(),
            nullable=False,
            comment="Number of requests",
        ),
        sa.Column(
            "tokens_used",
            sa.Integer(),
            nullable=False,
            comment="Total tokens consumed",
        ),
        sa.Column(
            "total_cost", sa.Float(), nullable=False, comment="Total cost"
        ),
        sa.Column(
            "success_rate",
            sa.Float(),
            nullable=False,
            comment="Success rate percentage",
        ),
        sa.Column(
            "created_by_user_id",
            sa.String(),
            nullable=True,
            comment="Optional foreign key to UserModel",
        ),
        sa.Column(
            "updated_by_user_id",
            sa.String(),
            nullable=True,
            comment="Optional foreign key to UserModel",
        ),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_by_user_id", sa.String(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        comment="Daily statistics for AI usage by provider and model",
        info={
            "source_module": "extensions.ai.BLL_AI",
            "extension": "ai",
        },
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ai_statistic")
    op.drop_table("ai_requests")
    # ### end Alembic commands ###
