# SPDX-License-Identifier: AGPL-3.0-or-later
"""Rust SDK emitter — renders the shared IR into a reqwest-based client.

Renders directly from ``sdk.SDKModel`` (Rust has no existing emitter): a shared
``client.rs`` (a ``reqwest`` transport + ``SdkError``), one resource-client
struct per RouterMixin-tagged manager, and a ``mod.rs`` barrel. Every path and
body comes from the IR, so the Rust client matches the server, the TypeScript
client, and the Python client by construction. Output is deterministic
(pre-sorted resources, no timestamps).
"""

from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path
from typing import Any, List, Tuple, cast

import stringcase

from zephyrex.lib.Logging import logger
from zephyrex.sdk.SDKModel import (
    TYPE_OBJECT,
    TYPE_OBJECT_LIST,
    TYPE_QUERY,
    TYPE_STRING,
    TYPE_STRING_LIST,
    Operation,
    ResourceDescriptor,
    extract_resources,
    resolve_body_key,
)

# Destination for the generated Rust SDK. Unset -> generation is a no-op.
SDK_RS_OUTPUT_DIR_ENV = "SDK_RS_OUTPUT_DIR"

# Rust edition rustfmt/clippy target — pinned so formatting is reproducible.
SDK_RS_EDITION = "2021"

_GENERATED_HEADER = "// Generated by meta_sdk_rs. Do not edit by hand."

_RS_TYPES = {
    TYPE_OBJECT: "Value",
    TYPE_STRING: "&str",
    TYPE_OBJECT_LIST: "Vec<Value>",
    TYPE_STRING_LIST: "Vec<String>",
    TYPE_QUERY: "Option<Value>",
}

_CLIENT_RS = f"""{_GENERATED_HEADER}
use serde_json::Value;

/// Errors surfaced by the generated client.
#[derive(Debug)]
pub enum SdkError {{
    Http(reqwest::Error),
    Status(u16),
}}

impl From<reqwest::Error> for SdkError {{
    fn from(err: reqwest::Error) -> Self {{
        SdkError::Http(err)
    }}
}}

/// Minimal typed transport shared by every generated resource client.
pub struct HttpClient {{
    base_url: String,
    client: reqwest::Client,
}}

impl HttpClient {{
    pub fn new(base_url: impl Into<String>) -> Self {{
        Self {{
            base_url: base_url.into().trim_end_matches('/').to_string(),
            client: reqwest::Client::new(),
        }}
    }}

    pub async fn request(
        &self,
        method: &str,
        path: &str,
        body: Option<Value>,
        query: Option<Value>,
    ) -> Result<Value, SdkError> {{
        let url = format!("{{}}{{}}", self.base_url, path);
        let method = reqwest::Method::from_bytes(method.as_bytes())
            .unwrap_or(reqwest::Method::GET);
        let mut builder = self.client.request(method, &url);
        if let Some(Value::Object(map)) = query {{
            let params: Vec<(String, String)> = map
                .iter()
                .map(|(k, v)| (k.clone(), v.to_string()))
                .collect();
            builder = builder.query(&params);
        }}
        if let Some(payload) = body {{
            builder = builder.json(&payload);
        }}
        let response = builder.send().await?;
        let status = response.status();
        if !status.is_success() {{
            return Err(SdkError::Status(status.as_u16()));
        }}
        if status.as_u16() == 204 {{
            return Ok(Value::Null);
        }}
        Ok(response.json::<Value>().await?)
    }}
}}
"""


def _struct_name(resource: ResourceDescriptor) -> str:
    return f"{stringcase.pascalcase(resource.name)}Sdk"


def _module_name(resource: ResourceDescriptor) -> str:
    # IR field crosses the package boundary (no py.typed) so mypy widens it to
    # Any; the value is a snake_case str. See sdk/SDKGenerator.py's cast usage.
    return cast(str, resource.name)  # already snake_case


def _arg_list(operation: Operation) -> str:
    return ", ".join(
        f"{arg.name}: {_RS_TYPES[arg.type_token]}" for arg in operation.args
    )


def _path_expr(resource: ResourceDescriptor, operation: Operation) -> str:
    path = resource.endpoint + operation.path_suffix
    if "{id}" in path:
        fmt = path.replace("{id}", "{}")
        return f'&format!("{fmt}", id)'
    return f'"{path}"'


def _body(resource: ResourceDescriptor, operation: Operation) -> Tuple[str, str]:
    """Return ``(body_expr, prelude_stmt)`` for the request call."""
    if not operation.body:
        return "None", ""
    if (
        len(operation.body) == 1
        and resolve_body_key(operation.body[0], resource) is None
    ):
        return f"Some({operation.body[0].arg})", ""
    fields = []
    for field in operation.body:
        key = resolve_body_key(field, resource)
        fields.append(f'"{key}": {field.arg}')
    prelude = "let body = serde_json::json!({ " + ", ".join(fields) + " });"
    return "Some(body)", prelude


def _render_method(resource: ResourceDescriptor, operation: Operation) -> str:
    args = _arg_list(operation)
    signature_args = f", {args}" if args else ""
    body_expr, prelude = _body(resource, operation)
    query_expr = "query" if operation.has_query else "None"
    call = (
        f'self.http.request("{operation.http_method}", '
        f"{_path_expr(resource, operation)}, {body_expr}, {query_expr}).await"
    )
    prelude_line = f"        {prelude}\n" if prelude else ""
    return (
        f"    pub async fn {operation.name}(&self{signature_args}) "
        f"-> Result<Value, SdkError> {{\n"
        f"{prelude_line}"
        f"        {call}\n"
        f"    }}"
    )


def _render_resource(resource: ResourceDescriptor) -> str:
    methods = "\n\n".join(_render_method(resource, op) for op in resource.operations)
    struct = _struct_name(resource)
    return (
        f"{_GENERATED_HEADER}\n"
        f"use serde_json::Value;\n\n"
        f"use super::client::{{HttpClient, SdkError}};\n\n"
        f"/// Typed client for `{resource.endpoint}` "
        f"(source manager: {resource.manager_qualname}).\n"
        f"pub struct {struct}<'a> {{\n"
        f"    http: &'a HttpClient,\n"
        f"}}\n\n"
        f"impl<'a> {struct}<'a> {{\n"
        f"    pub fn new(http: &'a HttpClient) -> Self {{\n"
        f"        Self {{ http }}\n"
        f"    }}\n\n"
        f"{methods}\n"
        f"}}\n"
    )


def _render_mod(resources: List[ResourceDescriptor]) -> str:
    lines = [_GENERATED_HEADER, "pub mod client;"]
    for resource in resources:
        lines.append(f"pub mod {_module_name(resource)};")
    lines.append("")
    lines.append("pub use client::{HttpClient, SdkError};")
    for resource in resources:
        lines.append(f"pub use {_module_name(resource)}::{_struct_name(resource)};")
    return "\n".join(lines) + "\n"


def _format_rust_sources(files: List[Path]) -> None:
    """Rewrite the emitted files through ``rustfmt`` so they are canonical.

    Best-effort: when ``rustfmt`` is not on ``PATH`` the files are left as
    emitted (still valid Rust, just hand-formatted). Hand-matching rustfmt's
    method-chain wrapping in the templates is brittle across rustfmt versions,
    so the canonical formatter is the single source of truth for layout.
    """
    rustfmt = shutil.which("rustfmt")
    if not rustfmt:
        return
    subprocess.run(
        [rustfmt, "--edition", SDK_RS_EDITION, *[str(f) for f in files]],
        check=False,
        capture_output=True,
    )


def generate_rust_sdk(*, model_registry: Any) -> None:
    """Emit a Rust client SDK for every manager in the registry.

    Self-gates on ``SDK_RS_OUTPUT_DIR``; returns immediately when unset.
    """
    output = os.getenv(SDK_RS_OUTPUT_DIR_ENV)
    if not output:
        return

    resources = extract_resources(model_registry)
    out_dir = Path(output)
    out_dir.mkdir(parents=True, exist_ok=True)

    written: List[Path] = [out_dir / "client.rs"]
    (out_dir / "client.rs").write_text(_CLIENT_RS, encoding="utf-8")
    for resource in resources:
        resource_path = out_dir / f"{_module_name(resource)}.rs"
        resource_path.write_text(_render_resource(resource), encoding="utf-8")
        written.append(resource_path)
    mod_path = out_dir / "mod.rs"
    mod_path.write_text(_render_mod(resources), encoding="utf-8")
    written.append(mod_path)

    _format_rust_sources(written)

    logger.info(
        f"meta_sdk_rs: generated {len(resources)} Rust resource "
        f"client(s) into {output}"
    )
