# SPDX-License-Identifier: AGPL-3.0-or-later
"""TypeScript SDK emitter — renders the shared IR into a fetch-based client.

Unlike Python (which reuses ``sdk.SDKGenerator``), TypeScript has no existing
emitter, so this module renders directly from ``sdk.SDKModel``: a shared
``runtime.ts`` (a typed ``fetch`` wrapper), one ``<Resource>SDK`` class per
resource, and a barrel ``index.ts``. Every request path and body is taken from
the IR, so the generated client matches the server — and the Rust client — by
construction. Output is deterministic (resources arrive pre-sorted; no
timestamps), so regeneration is byte-stable and diff-friendly.
"""

from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path
from typing import Any, List, Optional, Tuple, cast

import stringcase

from zephyrex.lib.Logging import logger
from zephyrex.sdk.SDKModel import (
    TYPE_OBJECT,
    TYPE_OBJECT_LIST,
    TYPE_QUERY,
    TYPE_STRING,
    TYPE_STRING_LIST,
    Operation,
    ResourceDescriptor,
    extract_resources,
    resolve_body_key,
)

# Destination for the generated TypeScript SDK. Unset -> generation is a no-op.
SDK_TS_OUTPUT_DIR_ENV = "SDK_TS_OUTPUT_DIR"

_GENERATED_HEADER = "// Generated by meta_sdk_ts. Do not edit by hand."

_TS_TYPES = {
    TYPE_OBJECT: "Record<string, unknown>",
    TYPE_STRING: "string",
    TYPE_OBJECT_LIST: "Record<string, unknown>[]",
    TYPE_STRING_LIST: "string[]",
    TYPE_QUERY: "Record<string, unknown>",  # rendered optional at the call site
}

_RUNTIME_TS = f"""{_GENERATED_HEADER}

export interface RequestInit {{
  body?: unknown;
  query?: Record<string, unknown>;
}}

/** Minimal typed transport shared by every generated resource client. */
export class HttpClient {{
  constructor(
    private readonly baseUrl: string,
    private readonly headers: Record<string, string> = {{}},
  ) {{}}

  async request(method: string, path: string, init: RequestInit = {{}}): Promise<unknown> {{
    const url = new URL(this.baseUrl.replace(/\\/$/, "") + path);
    if (init.query) {{
      for (const [key, value] of Object.entries(init.query)) {{
        if (value !== undefined && value !== null) {{
          url.searchParams.set(key, String(value));
        }}
      }}
    }}
    const response = await fetch(url.toString(), {{
      method,
      headers: {{ "Content-Type": "application/json", ...this.headers }},
      body: init.body === undefined ? undefined : JSON.stringify(init.body),
    }});
    if (!response.ok) {{
      throw new Error(`${{method}} ${{path}} failed with status ${{response.status}}`);
    }}
    if (response.status === 204) {{
      return undefined;
    }}
    return response.json();
  }}
}}
"""


def _class_name(resource: ResourceDescriptor) -> str:
    return f"{stringcase.pascalcase(resource.name)}SDK"


def _method_name(operation: Operation) -> str:
    # stringcase is untyped and the IR field crosses the package boundary (no
    # py.typed), so mypy widens both to Any; the value is a str. Mirrors the
    # cast(str, ...) convention already used in sdk/SDKGenerator.py.
    return cast(str, stringcase.camelcase(operation.name))


def _arg_list(operation: Operation) -> str:
    parts: List[str] = []
    for arg in operation.args:
        optional = "?" if arg.type_token == TYPE_QUERY else ""
        parts.append(f"{arg.name}{optional}: {_TS_TYPES[arg.type_token]}")
    return ", ".join(parts)


def _path_literal(resource: ResourceDescriptor, operation: Operation) -> str:
    """Template literal for the request path, interpolating ``${id}`` if needed."""
    path = resource.endpoint + operation.path_suffix
    path = path.replace("{id}", "${id}")
    return f"`{path}`"


def _body_literal(resource: ResourceDescriptor, operation: Operation) -> str:
    """The object-literal body expression, or ``""`` when there is no body."""
    if not operation.body:
        return ""
    # A single unwrapped field means the argument *is* the body.
    if (
        len(operation.body) == 1
        and resolve_body_key(operation.body[0], resource) is None
    ):
        return cast(str, operation.body[0].arg)
    fields = []
    for field in operation.body:
        key = resolve_body_key(field, resource)
        fields.append(f'"{key}": {field.arg}')
    return "{ " + ", ".join(fields) + " }"


def _return_type(operation: Operation) -> str:
    return "Promise<void>" if operation.name == "delete" else "Promise<unknown>"


def _render_method(resource: ResourceDescriptor, operation: Operation) -> str:
    init_parts: List[str] = []
    body = _body_literal(resource, operation)
    if body:
        init_parts.append(f"body: {body}")
    if operation.has_query:
        init_parts.append("query")
    init = f", {{ {', '.join(init_parts)} }}" if init_parts else ""
    call = (
        f'this.http.request("{operation.http_method}", '
        f"{_path_literal(resource, operation)}{init})"
    )
    if operation.name == "delete":
        call = f"{call} as Promise<void>"
    return (
        f"  {_method_name(operation)}({_arg_list(operation)}): "
        f"{_return_type(operation)} {{\n    return {call};\n  }}"
    )


def _render_resource(resource: ResourceDescriptor) -> str:
    methods = "\n\n".join(_render_method(resource, op) for op in resource.operations)
    return (
        f"{_GENERATED_HEADER}\n"
        f'import {{ HttpClient }} from "./runtime";\n\n'
        f"/** Typed client for `{resource.endpoint}` "
        f"(source manager: {resource.manager_qualname}). */\n"
        f"export class {_class_name(resource)} {{\n"
        f"  constructor(private readonly http: HttpClient) {{}}\n\n"
        f"{methods}\n"
        f"}}\n"
    )


def _render_index(resources: List[ResourceDescriptor]) -> str:
    lines = [_GENERATED_HEADER, 'export { HttpClient } from "./runtime";']
    for resource in resources:
        cls = _class_name(resource)
        lines.append(f'export {{ {cls} }} from "./{cls}";')
    return "\n".join(lines) + "\n"


def resolve_ts_formatter() -> Optional[Tuple[str, List[str]]]:
    """Return ``(binary, write_args)`` for the first available TS formatter.

    Prettier is preferred, Biome (the workspace-standard TS toolchain) is the
    fallback. The formatter *check* in the test suite must resolve the same tool
    in the same order so the emitted layout and the checked layout agree. Returns
    ``None`` when no formatter is on ``PATH``.
    """
    prettier = shutil.which("prettier")
    if prettier:
        return prettier, ["--write"]
    biome = shutil.which("biome")
    if biome:
        return biome, ["format", "--write"]
    return None


def _format_typescript_sources(files: List[Path]) -> None:
    """Rewrite the emitted files through the canonical TS formatter if present.

    Best-effort: when no formatter is on ``PATH`` the files are left as emitted.
    """
    formatter = resolve_ts_formatter()
    if formatter is None:
        return
    binary, args = formatter
    subprocess.run(
        [binary, *args, *[str(f) for f in files]],
        check=False,
        capture_output=True,
    )


def generate_typescript_sdk(*, model_registry: Any) -> None:
    """Emit a TypeScript client SDK for every manager in the registry.

    Self-gates on ``SDK_TS_OUTPUT_DIR``; returns immediately when unset.
    """
    output = os.getenv(SDK_TS_OUTPUT_DIR_ENV)
    if not output:
        return

    resources = extract_resources(model_registry)
    out_dir = Path(output)
    out_dir.mkdir(parents=True, exist_ok=True)

    written: List[Path] = [out_dir / "runtime.ts"]
    (out_dir / "runtime.ts").write_text(_RUNTIME_TS, encoding="utf-8")
    for resource in resources:
        resource_path = out_dir / f"{_class_name(resource)}.ts"
        resource_path.write_text(_render_resource(resource), encoding="utf-8")
        written.append(resource_path)
    index_path = out_dir / "index.ts"
    index_path.write_text(_render_index(resources), encoding="utf-8")
    written.append(index_path)

    _format_typescript_sources(written)

    logger.info(
        f"meta_sdk_ts: generated {len(resources)} TypeScript resource "
        f"client(s) into {output}"
    )
