# SPDX-License-Identifier: AGPL-3.0-or-later
# Extension manifest (Item 20): what an installer reads before the extension
# class can be imported. It mirrors the class (name, version, description,
# dependencies); the class stays the source of truth and
# Manifest_parity_test keeps the two in step.

name = "sms"
version = "1.0.0"
description = "SMS through Twilio or Amazon SNS"
author = "ZephyrexTechnologies"
entry_module = "EXT_SMS"
minimum_framework_version = "0.0.0"

pip_dependencies = ["boto3>=1.26.0", "botocore>=1.29.0", "twilio>=9.0.0"]
system_dependencies = []
