"""initial schema

Revision ID: 175cfe29b4df
Revises:
Create Date: 2025-06-09 21:53:21.176039

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "175cfe29b4df"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ("ext_ai_agents",)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activities",
        sa.Column(
            "title", sa.String(), nullable=False, comment="Title of the activity"
        ),
        sa.Column(
            "body", sa.String(), nullable=False, comment="Body content of the activity"
        ),
        sa.Column(
            "state", sa.Integer(), nullable=True, comment="State of the activity"
        ),
        sa.Column(
            "invocation_instance_id",
            sa.String(),
            nullable=True,
            comment="ID of the InvocationInstance (turn) this activity belongs to",
        ),
        sa.Column(
            "ability_id", sa.String(), nullable=False, comment="ID of the ability"
        ),
        sa.Column(
            "artifact_id",
            sa.String(),
            nullable=True,
            comment="ID of the artifact created by this activity",
        ),
        sa.Column(
            "provider_id",
            sa.String(),
            nullable=True,
            comment="ID of the provider used for this activity",
        ),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("created_by_user_id", sa.String(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("updated_by_user_id", sa.String(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_by_user_id", sa.String(), nullable=True),
        sa.Column(
            "parent_id", sa.String(), nullable=True, comment="ID of the parent record"
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["activities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="An Activity represents an action an Agent takes (or took) during a turn. A turn's activities belong to its InvocationInstance via invocation_instance_id; the root activity carries it and children inherit it through parent_id. Activities are typed using ability_id. Sub-actions (e.g., steps in a web search) are indicated with the parent_id field. Activities can optionally produce an Artifact.",
        info={
            "source_module": "extensions.ai_agents.BLL_AI_Agents",
            "extension": "ai_agents",
        },
    )
    op.create_table(
        "agents",
        sa.Column(
            "team_id",
            sa.String(),
            nullable=True,
            comment="Optional foreign key to Team",
        ),
        sa.Column(
            "user_id",
            sa.String(),
            nullable=True,
            comment="Optional foreign key to User",
        ),
        sa.Column("name", sa.String(), nullable=False, comment="Name of the agent"),
        sa.Column(
            "favourite",
            sa.Boolean(),
            nullable=False,
            server_default="0",
            comment="Whether the agent is marked as favourite",
        ),
        sa.Column(
            "rotation_id", sa.String(), nullable=True, comment="ID of the rotation"
        ),
        sa.Column(
            "image_url", sa.String(), nullable=True, comment="URL of the agent image"
        ),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("created_by_user_id", sa.String(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("updated_by_user_id", sa.String(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_by_user_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        comment="An Agent represents a container of configuration and memories with which to communicate.",
        info={
            "source_module": "extensions.ai_agents.BLL_AI_Agents",
            "extension": "ai_agents",
        },
    )
    op.create_table(
        "projects",
        sa.Column(
            "team_id",
            sa.String(),
            nullable=True,
            comment="Optional foreign key to Team",
        ),
        sa.Column("user_id", sa.String(), nullable=False, comment="ID of the user"),
        sa.Column("name", sa.String(), nullable=False, comment="The name"),
        sa.Column(
            "description",
            sa.String(),
            nullable=True,
            comment="Description of the project",
        ),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("created_by_user_id", sa.String(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("updated_by_user_id", sa.String(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_by_user_id", sa.String(), nullable=True),
        sa.Column(
            "parent_id", sa.String(), nullable=True, comment="ID of the parent record"
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="A Project represents an enclosing organizational container for Conversations with additional context injection options.",
        info={
            "source_module": "extensions.ai_agents.BLL_AI_Agents",
            "extension": "ai_agents",
        },
    )
    op.create_table(
        "project_context_prompts",
        sa.Column("prompt_id", sa.String(), nullable=False, comment="ID of the prompt"),
        sa.Column(
            "project_id", sa.String(), nullable=False, comment="ID of the project"
        ),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("created_by_user_id", sa.String(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("updated_by_user_id", sa.String(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_by_user_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="A ProjectContextPrompt represents the association of a Prompt with a Project for context injection.",
        info={
            "source_module": "extensions.ai_agents.BLL_AI_Agents",
            "extension": "ai_agents",
        },
    )
    op.create_table(
        "project_context_providers",
        sa.Column(
            "provider_id",
            sa.String(),
            nullable=False,
            comment="ID of the provider extension",
        ),
        sa.Column(
            "project_id", sa.String(), nullable=False, comment="ID of the project"
        ),
        sa.Column(
            "context_resource",
            sa.String(),
            nullable=True,
            comment="Resource identifier for context",
        ),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("created_by_user_id", sa.String(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("updated_by_user_id", sa.String(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_by_user_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="A ProjectContextProvider represents the association of a Provider with a Project for context injection.",
        info={
            "source_module": "extensions.ai_agents.BLL_AI_Agents",
            "extension": "ai_agents",
        },
    )
    op.create_table(
        "agent_context_prompts",
        sa.Column("prompt_id", sa.String(), nullable=False, comment="ID of the prompt"),
        sa.Column("agent_id", sa.String(), nullable=False, comment="ID of the agent"),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("created_by_user_id", sa.String(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("updated_by_user_id", sa.String(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_by_user_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="An AgentContextPrompt represents the association of a Prompt with an Agent for context injection.",
        info={
            "source_module": "extensions.ai_agents.BLL_AI_Agents",
            "extension": "ai_agents",
        },
    )
    op.create_table(
        "agent_abilities",
        sa.Column(
            "ability_id", sa.String(), nullable=False, comment="ID of the ability"
        ),
        sa.Column("agent_id", sa.String(), nullable=False, comment="ID of the agent"),
        sa.Column(
            "enabled",
            sa.Boolean(),
            nullable=False,
            server_default="1",
            comment="Whether this ability is enabled for the agent",
        ),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("created_by_user_id", sa.String(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("updated_by_user_id", sa.String(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_by_user_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment=(
            "An AgentAbility grants an Agent permission to invoke an Ability as "
            "a tool. It is the agent's default-deny allowlist: an agent may "
            "invoke only the abilities for which it has an enabled AgentAbility."
        ),
        info={
            "source_module": "extensions.ai_agents.BLL_AI_Agents",
            "extension": "ai_agents",
        },
    )
    op.create_table(
        "agent_memories",
        sa.Column(
            "key",
            sa.String(),
            nullable=False,
            comment="Memory key (unique per agent)",
        ),
        sa.Column("content", sa.String(), nullable=False, comment="Memory content"),
        sa.Column("agent_id", sa.String(), nullable=False, comment="ID of the agent"),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("created_by_user_id", sa.String(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("updated_by_user_id", sa.String(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_by_user_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment=(
            "An AgentMemory is a keyed short-term (working) memory for an Agent, "
            "injected into each turn's prompt and prunable via the trim ability."
        ),
        info={
            "source_module": "extensions.ai_agents.BLL_AI_Agents",
            "extension": "ai_agents",
        },
    )
    op.create_table(
        "conversation_agents",
        sa.Column("agent_id", sa.String(), nullable=False, comment="ID of the agent"),
        sa.Column(
            "conversation_id",
            sa.String(),
            nullable=False,
            comment="ID of the conversation",
        ),
        sa.Column(
            "active",
            sa.Boolean(),
            nullable=False,
            server_default="1",
            comment="Whether the agent is actively participating",
        ),
        sa.Column(
            "auto_respond",
            sa.Boolean(),
            nullable=False,
            server_default="0",
            comment="Whether the agent should automatically respond",
        ),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("created_by_user_id", sa.String(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("updated_by_user_id", sa.String(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_by_user_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="ConversationAgent represents an AI agent's participation in a conversation, allowing agents to be conversation participants alongside users.",
        info={
            "source_module": "extensions.ai_agents.BLL_AI_Agents",
            "extension": "ai_agents",
        },
    )
    op.create_table(
        "provider_instance_agent_abilities",
        sa.Column(
            "provider_instance_id",
            sa.String(),
            nullable=False,
            comment="ID of the provider instance",
        ),
        sa.Column("agent_id", sa.String(), nullable=False, comment="ID of the agent"),
        sa.Column(
            "state",
            sa.Boolean(),
            nullable=False,
            server_default="0",
            comment="Whether this ability is enabled for this agent",
        ),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("created_by_user_id", sa.String(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("updated_by_user_id", sa.String(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_by_user_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="An ProviderInstanceAgentAbility represents a difference between THIS Agent's ability state and the state of the ProviderInstanceAbility. Nonpresence of a record means that the Agent's ability state is the same as the ProviderInstanceAbility - note that this is ignored if the ExtensionInstanceAbility is forced.",
        info={
            "source_module": "extensions.ai_agents.BLL_AI_Agents",
            "extension": "ai_agents",
        },
    )
    op.create_table(
        "provider_instance_agents",
        sa.Column(
            "provider_instance_id",
            sa.String(),
            nullable=False,
            comment="ID of the provider instance",
        ),
        sa.Column("agent_id", sa.String(), nullable=False, comment="ID of the agent"),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("created_by_user_id", sa.String(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("updated_by_user_id", sa.String(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_by_user_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="A ProviderInstanceAgent represents a link between a ProviderInstance and an Agent (typically for extension providers as AI providers go through rotations). Nonpresence of a record means that the Agent does not have access to the ProviderInstance.",
        info={
            "source_module": "extensions.ai_agents.BLL_AI_Agents",
            "extension": "ai_agents",
        },
    )
    op.create_table(
        "invocation_triggers",
        sa.Column(
            "team_id",
            sa.String(),
            nullable=True,
            comment="Optional foreign key to Team",
        ),
        sa.Column(
            "user_id",
            sa.String(),
            nullable=True,
            comment="Optional foreign key to User",
        ),
        sa.Column(
            "agent_id",
            sa.String(),
            nullable=True,
            comment="Agent whose turn this trigger fires",
        ),
        sa.Column(
            "invocation_type",
            sa.String(),
            nullable=False,
            comment="How the agent turn is triggered: 'schedule' | 'timer' | 'event'",
        ),
        sa.Column(
            "enabled",
            sa.Boolean(),
            nullable=False,
            server_default="1",
            comment="Whether this trigger is active",
        ),
        sa.Column(
            "cron",
            sa.String(),
            nullable=True,
            comment="Cron expression (invocation_type='schedule')",
        ),
        sa.Column(
            "interval_seconds",
            sa.Integer(),
            nullable=True,
            comment="Delay/interval in seconds (invocation_type='timer')",
        ),
        sa.Column(
            "one_shot",
            sa.Boolean(),
            nullable=False,
            server_default="0",
            comment="Timer only: fire once after interval_seconds then disable",
        ),
        sa.Column(
            "event_source",
            sa.String(),
            nullable=True,
            comment="Event source (invocation_type='event')",
        ),
        sa.Column(
            "event_filter",
            sa.String(),
            nullable=True,
            comment="JSON-encoded match criteria against the event",
        ),
        sa.Column(
            "invocation_payload",
            sa.String(),
            nullable=True,
            comment="Default prompt/context handed to the agent turn when this fires",
        ),
        sa.Column(
            "last_fired_at",
            sa.DateTime(),
            nullable=True,
            comment="When this trigger last fired",
        ),
        sa.Column(
            "next_fire_at",
            sa.DateTime(),
            nullable=True,
            comment="Next scheduled fire time (schedule/timer)",
        ),
        sa.Column(
            "fire_count",
            sa.Integer(),
            nullable=False,
            server_default="0",
            comment="Number of times this trigger has fired",
        ),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("created_by_user_id", sa.String(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("updated_by_user_id", sa.String(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_by_user_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        comment="An InvocationTrigger is a standing listener that triggers an Agent to take a turn - on a schedule (cron), a timer (interval), or an external event (email, conversation message, webhook). It fires many times; each firing is an InvocationInstance. Tasks are a type of trigger.",
        info={
            "source_module": "extensions.ai_agents.BLL_AI_Agents",
            "extension": "ai_agents",
        },
    )
    op.create_table(
        "invocation_instances",
        sa.Column(
            "invocation_trigger_id",
            sa.String(),
            nullable=True,
            comment="Trigger that fired this instance (null for ad-hoc/manual turns)",
        ),
        sa.Column(
            "agent_id",
            sa.String(),
            nullable=False,
            comment="Agent whose turn this instance is",
        ),
        sa.Column(
            "team_id",
            sa.String(),
            nullable=True,
            comment="Optional foreign key to Team",
        ),
        sa.Column(
            "user_id",
            sa.String(),
            nullable=True,
            comment="Optional foreign key to User",
        ),
        sa.Column(
            "status",
            sa.String(),
            nullable=False,
            server_default="pending",
            comment="Lifecycle: 'pending' | 'running' | 'succeeded' | 'failed'",
        ),
        sa.Column(
            "trigger_message_id",
            sa.String(),
            nullable=True,
            comment="Message that fired this instance (conversation_message events)",
        ),
        sa.Column(
            "payload",
            sa.String(),
            nullable=True,
            comment="Prompt/context handed to this specific firing",
        ),
        sa.Column(
            "error",
            sa.String(),
            nullable=True,
            comment="Error detail when status='failed'",
        ),
        sa.Column(
            "started_at",
            sa.DateTime(),
            nullable=True,
            comment="When the turn began executing",
        ),
        sa.Column(
            "completed_at",
            sa.DateTime(),
            nullable=True,
            comment="When the turn finished",
        ),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("created_by_user_id", sa.String(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("updated_by_user_id", sa.String(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_by_user_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["invocation_trigger_id"],
            ["invocation_triggers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="An InvocationInstance is a single firing of an InvocationTrigger - one agent turn. It records the cause (trigger and/or triggering message), the context handed to the turn, and its lifecycle status; the turn's Activity tree links to it via invocation_instance_id.",
        info={
            "source_module": "extensions.ai_agents.BLL_AI_Agents",
            "extension": "ai_agents",
        },
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("invocation_instances")
    op.drop_table("invocation_triggers")
    op.drop_table("provider_instance_agents")
    op.drop_table("provider_instance_agent_abilities")
    op.drop_table("conversation_agents")
    op.drop_table("agent_memories")
    op.drop_table("agent_abilities")
    op.drop_table("agent_context_prompts")
    op.drop_table("agents")
    op.drop_table("projects")
    op.drop_table("project_context_providers")
    op.drop_table("project_context_prompts")
    op.drop_table("activities")
    # ### end Alembic commands ###
