from sqlalchemy import Column, String
from sqlalchemy.orm import relationship

from serverframework.database.AbstractDatabaseEntity import BaseMixin, UpdateMixin, create_foreign_key
from serverframework.database.Base import Base
from serverframework.database.DB_Projects import Project
from serverframework.database.DB_Providers import Provider
from serverframework.extensions.ai_agents.DB_AI_Agents import Agent
from serverframework.extensions.chains.DB_Chains import Chain
from serverframework.extensions.conversations.DB_Conversations import Conversation
from serverframework.extensions.prompts.DB_Prompts import Prompt
from serverframework.extensions.tasks.DB_Tasks import Task


class Label(Base, BaseMixin):
    __tablename__ = "labels"
    name = Column(String, unique=True, nullable=False)
    description = Column(String, nullable=True)
    color = Column(String, nullable=True)
    __table_args__ = {
        "comment": "A Label represents a global tag that can be applied to anything. These should be lower kebab case and concise. Generally these are generated by models and applied, but can be customized. Common parent table for statistical analysis."
    }


class AgentLabel(Base, BaseMixin, UpdateMixin):
    __tablename__ = "agent_labels"
    agent_id = create_foreign_key(Agent)
    label_id = create_foreign_key(Label)
    agent = relationship(Agent.__name__, backref="agent_labels")
    label = relationship(Label.__name__, backref="agent_labels")
    __table_args__ = {
        "comment": "An AgentLabel represents a link between an Agent and a Label (the Label is applied to the Agent)."
    }


Label.agents = relationship(AgentLabel.__name__, backref="label")
Agent.labels = relationship(AgentLabel.__name__, backref="agent")


class PromptLabel(Base, BaseMixin, UpdateMixin):
    __tablename__ = "prompt_labels"
    label_id = create_foreign_key(Label)
    prompt_id = create_foreign_key(Prompt)
    prompt = relationship(Prompt.__name__, backref="prompt_labels")
    label = relationship(Label.__name__, backref="prompt_labels")
    __table_args__ = {
        "comment": "A PromptLabel represents a link between a Prompt and a Label (the Label is applied to the Prompt)."
    }


Label.prompts = relationship(PromptLabel.__name__, backref="label")
Prompt.labels = relationship(PromptLabel.__name__, backref="prompt")


class ChainLabel(Base, BaseMixin, UpdateMixin):
    __tablename__ = "chain_labels"
    label_id = create_foreign_key(Label)
    chain_id = create_foreign_key(Chain)
    chain = relationship(Chain.__name__, backref="labels")
    label = relationship(Label.__name__, backref="chains")
    __table_args__ = {
        "comment": "A ChainLabel represents a link between a Chain and a Label (the Label is applied to the Chain)."
    }


Label.chains = relationship(ChainLabel.__name__, backref="label")
Chain.labels = relationship(ChainLabel.__name__, backref="chain")


class ProviderLabel(Base, BaseMixin, UpdateMixin):
    __tablename__ = "provider_labels"
    label_id = create_foreign_key(Label)
    provider_id = create_foreign_key(Provider)
    provider = relationship(Provider.__name__, backref="labels")
    label = relationship(Label.__name__, backref="providers")
    __table_args__ = {
        "comment": "A ProviderLabel represents a link between a Provider and a Label (the Label is applied to the Provider). These are typically used for generation modes."
    }


Label.providers = relationship(ProviderLabel.__name__, backref="label")
Provider.labels = relationship(ProviderLabel.__name__, backref="provider")


class TaskLabel(Base, BaseMixin, UpdateMixin):
    __tablename__ = "task_labels"
    label_id = create_foreign_key(Label)
    task_id = create_foreign_key(Task)
    task = relationship(Task.__name__, backref="labels")
    label = relationship(Label.__name__, backref="tasks")
    __table_args__ = {
        "comment": "A TaskLabel represents a link between a Task and a Label (the Label is applied to the Task)."
    }


Label.tasks = relationship(TaskLabel.__name__, backref="label")
Task.labels = relationship(TaskLabel.__name__, backref="task")


class ProjectLabel(Base, BaseMixin, UpdateMixin):
    __tablename__ = "project_labels"
    label_id = create_foreign_key(Label)
    project_id = create_foreign_key(Project)
    project = relationship(Project.__name__, backref="labels")
    label = relationship(Label.__name__, backref="projects")
    __table_args__ = {
        "comment": "A ProjectLabel represents a link between a Project and a Label (the Label is applied to the Project)."
    }


Label.projects = relationship(ProjectLabel.__name__, backref="label")
Project.labels = relationship(ProjectLabel.__name__, backref="project")


class ConversationLabel(Base, BaseMixin, UpdateMixin):
    __tablename__ = "conversation_labels"
    label_id = create_foreign_key(Label)
    conversation_id = create_foreign_key(Conversation)
    conversation = relationship(Conversation.__name__, backref="labels")
    label = relationship(Label.__name__, backref="conversations")
    __table_args__ = {
        "comment": "A ConversationLabel represents a link between a Conversation and a Label (the Label is applied to the Conversation). This can be topics, generation modes, etc."
    }


Label.conversations = relationship(ConversationLabel.__name__, backref="label")
Conversation.labels = relationship(ConversationLabel.__name__, backref="conversation")
