"""Regenerate ``EXT.Contracts.md`` from ``EXT.Contracts.json``.

The manifest is the source of truth for the framework's public-primitive
surface (Item 52). For every entry the generator imports the module,
resolves the symbol via ``getattr``, captures the signature for callables
and the first docstring line, and emits a deterministic markdown document.

Run ``python -m serverframework.extensions.build_contracts_md`` to refresh
``EXT.Contracts.md`` in place. ``--check`` regenerates to a string and exits
non-zero with a unified diff if the on-disk file disagrees.
"""

from __future__ import annotations

import argparse
import ast
import difflib
import importlib
import inspect
import json
import re
import sys
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple

HERE = Path(__file__).resolve().parent
MANIFEST_PATH = HERE / "EXT.Contracts.json"
MARKDOWN_PATH = HERE / "EXT.Contracts.md"

BANNER = (
    "<!-- AUTOGENERATED — DO NOT EDIT BY HAND.\n"
    "     Edit `EXT.Contracts.json` and run\n"
    "     `python -m serverframework.extensions.build_contracts_md`. -->\n"
)


def _module_file(module_name: str) -> Optional[Path]:
    """Map a dotted module path to its source file via the package layout."""
    parts = module_name.split(".")
    if not parts or parts[0] != "serverframework":
        return None
    candidate = HERE.parent.joinpath(*parts[1:]).with_suffix(".py")
    return candidate if candidate.is_file() else None


def _ast_has_symbol(module_name: str, symbol: str) -> bool:
    path = _module_file(module_name)
    if path is None:
        return False
    tree = ast.parse(path.read_text())
    for node in tree.body:
        if isinstance(node, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)):
            if node.name == symbol:
                return True
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == symbol:
                    return True
    return False


def _resolve(entry: Dict[str, Any]) -> Tuple[Optional[Any], bool]:
    """Return (symbol, imported). symbol is None if neither import nor AST find it."""
    module_name = entry["module"]
    symbol_name = entry["name"]
    try:
        module = importlib.import_module(module_name)
    except ModuleNotFoundError:
        return (None, False) if not _ast_has_symbol(module_name, symbol_name) else (None, False)
    symbol = getattr(module, symbol_name, None)
    if symbol is None:
        return (None, False)
    return (symbol, True)


_MEMADDR_RE = re.compile(r" at 0x[0-9a-fA-F]+")


def _signature_text(symbol: Any) -> Optional[str]:
    if not callable(symbol) and not inspect.isclass(symbol):
        return None
    try:
        sig = inspect.signature(symbol)
    except (TypeError, ValueError):
        return None
    text = f"{getattr(symbol, '__name__', '?')}{sig}"
    # Default-arg reprs sometimes embed memory addresses (e.g., lambdas);
    # scrub them so the rendered signature is byte-stable across runs.
    return _MEMADDR_RE.sub("", text)


def _docstring_summary(symbol: Any) -> Optional[str]:
    doc = inspect.getdoc(symbol)
    if not doc:
        return None
    for line in doc.splitlines():
        line = line.strip()
        if line:
            return line
    return None


def _format_entry(entry: Dict[str, Any]) -> List[str]:
    symbol, imported = _resolve(entry)
    lines: List[str] = []
    lines.append(f"### `{entry['name']}` ({entry['kind']})")
    lines.append("")
    lines.append(f"- Module: `{entry['module']}`")
    if imported and symbol is not None:
        sig = _signature_text(symbol)
        if sig:
            lines.append(f"- Signature: `{sig}`")
        live_doc = _docstring_summary(symbol)
        if live_doc and live_doc != entry.get("summary"):
            lines.append(f"- Live docstring: {live_doc}")
    else:
        lines.append("- Signature: _import failed; AST-only entry_")
    lines.append("")
    lines.append(entry["summary"])
    invariants = entry.get("invariants") or []
    if invariants:
        lines.append("")
        lines.append("Invariants:")
        for inv in invariants:
            lines.append(f"- {inv}")
    lines.append("")
    return lines


def _render(manifest: Dict[str, Any]) -> str:
    out: List[str] = []
    out.append(BANNER)
    out.append("# Public Primitives Contract")
    out.append("")
    out.append(
        "Canonical enumeration of every primitive an extension author may rely on as"
        " stable. Symbols not listed are internal and may change without notice."
    )
    out.append("")
    out.append(
        "The manifest at `EXT.Contracts.json` is the source of truth. CI fails on drift"
        " between the manifest and `serverframework.__all__` (Item 68) and between this"
        " file and the manifest."
    )
    out.append("")
    for group in manifest["groups"]:
        out.append(f"## {group['title']}")
        out.append("")
        sorted_entries = sorted(group["entries"], key=lambda e: e["name"])
        for entry in sorted_entries:
            out.extend(_format_entry(entry))
    return "\n".join(out).rstrip() + "\n"


def _load_manifest() -> Dict[str, Any]:
    return json.loads(MANIFEST_PATH.read_text())


def main(argv: Optional[Iterable[str]] = None) -> int:
    parser = argparse.ArgumentParser(prog="build_contracts_md")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero with a unified diff if EXT.Contracts.md is out of date.",
    )
    args = parser.parse_args(list(argv) if argv is not None else None)

    manifest = _load_manifest()
    rendered = _render(manifest)

    if args.check:
        existing = MARKDOWN_PATH.read_text() if MARKDOWN_PATH.exists() else ""
        if existing == rendered:
            return 0
        diff = difflib.unified_diff(
            existing.splitlines(keepends=True),
            rendered.splitlines(keepends=True),
            fromfile=str(MARKDOWN_PATH),
            tofile=f"{MARKDOWN_PATH} (regenerated)",
        )
        sys.stdout.writelines(diff)
        return 1

    MARKDOWN_PATH.write_text(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
