"""initial schema

Revision ID: 95260599be0e
Revises:
Create Date: 2025-06-09 21:53:24.139925

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "95260599be0e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ("ext_ai_prompts",)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prompts",
        sa.Column(
            "team_id",
            sa.String(),
            nullable=True,
            comment="Optional foreign key to Team",
        ),
        sa.Column(
            "user_id",
            sa.String(),
            nullable=True,
            comment="Optional foreign key to User",
        ),
        sa.Column(
            "description", sa.String(), nullable=False, comment="The description"
        ),
        sa.Column("name", sa.String(), nullable=False, comment="The name"),
        sa.Column(
            "favourite",
            sa.Boolean(),
            nullable=False,
            comment="Whether this prompt is marked as a favorite",
        ),
        sa.Column(
            "content", sa.String(), nullable=False, comment="The content of the prompt"
        ),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("created_by_user_id", sa.String(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("updated_by_user_id", sa.String(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_by_user_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="A Prompt represents a stored prompt that can be used in Conversations and elsewhere. Variable injection for prompts is expected in the form {VARIABLE_NAME}.",
        info={
            "source_module": "extensions.ai_prompts.BLL_AI_Prompts",
            "extension": "ai_prompts",
        },
    )
    op.create_table(
        "prompt_arguments",
        sa.Column(
            "prompt_id",
            sa.String(),
            nullable=False,
            comment="The ID of the related prompt",
        ),
        sa.Column("name", sa.String(), nullable=False, comment="The name"),
        sa.Column(
            "default_value",
            sa.String(),
            nullable=True,
            comment="Default value for this argument",
        ),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("created_by_user_id", sa.String(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("updated_by_user_id", sa.String(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_by_user_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["prompt_id"],
            ["prompts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="A PromptArgument represents a variable injection for a Prompt.",
        info={
            "source_module": "extensions.ai_prompts.BLL_AI_Prompts",
            "extension": "ai_prompts",
        },
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("prompt_arguments")
    op.drop_table("prompts")
    # ### end Alembic commands ###
