"""Guardrail tests for the EXT.Contracts.md generator (Item 52)."""

from __future__ import annotations

import ast
import importlib
import json
from pathlib import Path

import pytest

from zephyrex.extensions import build_contracts_md as gen


MANIFEST = json.loads(gen.MANIFEST_PATH.read_text())


def _all_entries():
    for group in MANIFEST["groups"]:
        for entry in group["entries"]:
            yield entry


@pytest.mark.parametrize(
    "entry",
    list(_all_entries()),
    ids=[f"{e['module']}.{e['name']}" for e in _all_entries()],
)
def test_manifest_entries_resolve(entry):
    """Every manifest entry resolves either via import or AST scan — no orphans."""
    name = entry["name"]
    module_name = entry["module"]

    try:
        module = importlib.import_module(module_name)
    except ModuleNotFoundError:
        path = gen._module_file(module_name)
        assert path is not None, f"module {module_name} has no on-disk source"
        tree = ast.parse(path.read_text())
        names = {
            node.name
            for node in tree.body
            if isinstance(node, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef))
        }
        assert name in names, f"{module_name}.{name} not found via AST"
        return

    assert hasattr(module, name), f"{module_name} does not export {name}"


def test_markdown_is_in_sync():
    """`build_contracts_md.main(['--check'])` must succeed against the committed file.

    Runs in a subprocess so model-registry mutations from earlier tests
    (e.g. @extension_model side effects) cannot contaminate the check.
    """
    import subprocess
    import sys

    result = subprocess.run(
        [sys.executable, "-m", "zephyrex.extensions.build_contracts_md", "--check"],
        cwd=Path(__file__).resolve().parents[2],
        capture_output=True,
        text=True,
        timeout=30,
    )
    assert result.returncode == 0, (
        "EXT.Contracts.md is stale; rerun build_contracts_md to regenerate.\n"
        f"stderr: {result.stderr[-500:]}"
    )


def test_banner_present_in_committed_markdown():
    """The committed markdown must carry the autogenerated banner."""
    text = Path(gen.MARKDOWN_PATH).read_text()
    assert text.startswith("<!-- AUTOGENERATED"), "missing autogenerated banner"
