# SPDX-License-Identifier: AGPL-3.0-or-later
"""Keep what installers read in step with what extensions declare.

An extension's pip requirements live in code: its class and its providers
(``AbstractStaticExtension.pip_requirements``). Two copies are read before
that code can be imported: the extension's ``manifest.toml``
(``pip_dependencies``) and its ``zephyrex[<extension>]`` extra in
``pyproject.toml``, between the generated-block markers. This rewrites both
from the code; ``--check`` reports drift and exits non-zero instead (the
test suite runs it).

Reading the code imports every extension, and with them their optional
packages, so it needs every extra installed. ``--from-manifests`` instead
checks ``pyproject.toml``'s extras against the manifests alone, importing no
extension: what a release checks on a core-only install, after the commit
gate has held the manifests to the code.

    python -m zephyrex.extensions.sync_dependencies [--check] [--from-manifests]
"""

import argparse
import importlib
import inspect
import json
import re
import sys
import tomllib
from pathlib import Path
from typing import Dict, List, Tuple

_EXTENSIONS = Path(__file__).resolve().parent
_PROJECT = _EXTENSIONS.parents[2] / "pyproject.toml"
_BEGIN = "# BEGIN generated by zephyrex.extensions.sync_dependencies"
_END = "# END generated by zephyrex.extensions.sync_dependencies"
_MANIFEST_LINE = re.compile(r"^pip_dependencies = .*$", re.MULTILINE)


def extra_name(extension: str) -> str:
    """``auth_mfa`` is installed as ``zephyrex[auth-mfa]``."""
    return extension.replace("_", "-")


def extension_folders() -> List[Path]:
    return sorted(
        entry for entry in _EXTENSIONS.iterdir() if (entry / "manifest.toml").is_file()
    )


def declared_requirements() -> Dict[str, List[str]]:
    """Each extension's pip requirements, from its code."""
    from zephyrex.extensions.AbstractExtensionProvider import (
        AbstractStaticExtension,
    )

    requirements: Dict[str, List[str]] = {}
    for folder in extension_folders():
        for module_file in sorted(folder.glob("EXT_*.py")):
            if module_file.stem.endswith("_test"):
                continue
            module = importlib.import_module(
                f"zephyrex.extensions.{folder.name}.{module_file.stem}"
            )
            for _, cls in inspect.getmembers(module, inspect.isclass):
                if (
                    issubclass(cls, AbstractStaticExtension)
                    and cls.__module__ == module.__name__
                    and getattr(cls, "name", None) == folder.name
                ):
                    requirements[folder.name] = cls.pip_requirements()
    return requirements


def manifest_requirements() -> Dict[str, List[str]]:
    """Each extension's pip requirements as its manifest states them: what
    an installer reads, without importing the extension."""
    return {
        folder.name: list(
            tomllib.loads((folder / "manifest.toml").read_text())["pip_dependencies"]
        )
        for folder in extension_folders()
    }


def _toml_list(values: List[str]) -> str:
    return json.dumps(values)


def expected_files(requirements: Dict[str, List[str]]) -> Dict[Path, str]:
    """Every file this tool owns, as it should read for ``requirements``."""
    files: Dict[Path, str] = {}
    for folder in extension_folders():
        manifest = folder / "manifest.toml"
        line = f"pip_dependencies = {_toml_list(requirements[folder.name])}"
        text = manifest.read_text()
        if not _MANIFEST_LINE.search(text):
            raise ValueError(f"{manifest}: no pip_dependencies line")
        files[manifest] = _MANIFEST_LINE.sub(line, text, count=1)

    project = _PROJECT.read_text()
    start, end = project.find(_BEGIN), project.find(_END)
    if start < 0 or end < start:
        raise ValueError(f"{_PROJECT}: generated-block markers not found")
    # Hand-written extras outside the block (core's own, e.g. ``cache``);
    # ``all`` installs them too, but never the development tooling.
    outside = tomllib.loads(project[:start] + project[end + len(_END) :])
    core_extras = sorted(
        set(outside["project"].get("optional-dependencies", {})) - {"dev"}
    )
    extension_extras = [extra_name(name) for name in sorted(requirements)]

    block = [_BEGIN]
    for name in sorted(requirements):
        block.append(f"{extra_name(name)} = {_toml_list(requirements[name])}")
    block.append(
        "all = "
        + _toml_list(
            [f"zephyrex[{extra}]" for extra in sorted(core_extras + extension_extras)]
        )
    )
    block.append(_END)
    files[_PROJECT] = project[:start] + "\n".join(block) + project[end + len(_END) :]
    return files


def drift(from_manifests: bool = False) -> List[Tuple[Path, str]]:
    requirements = (
        manifest_requirements() if from_manifests else declared_requirements()
    )
    return [
        (path, text)
        for path, text in expected_files(requirements).items()
        if path.read_text() != text
    ]


def main(argv: List[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true")
    parser.add_argument(
        "--from-manifests",
        action="store_true",
        help="hold pyproject's extras to the manifests, importing no extension",
    )
    args = parser.parse_args(argv)
    from zephyrex.lib.Logging import logger

    stale = drift(from_manifests=args.from_manifests)
    if args.check:
        for path, _ in stale:
            logger.error(f"out of date (run sync_dependencies): {path}")
        return 1 if stale else 0
    for path, text in stale:
        path.write_text(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
