name: Metadata Sync Trigger

on:
  push:
    branches:
      - main
      - dev
  schedule:
    - cron: '0 2 * * *'  # Every day at 2 AM UTC
  workflow_dispatch:

jobs:
  call-reusable-sync:
    name: Call Reusable Metadata Sync
    uses: JamesonRGrieve/Workflows/.github/workflows/sync-meta.yml@main
    with:
      sync_labels: true
      sync_templates: true
      sync_milestones: true
      sync_branch_protections: true
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
