name: PR Tests

on:
  pull_request:

jobs:
  run-tests:
    name: Run Pytest Comparison
    uses: JamesonRGrieve/Workflows/.github/workflows/run-branch-test.yml@main
    with:
      target_branch: ${{ github.base_ref }}
    secrets:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      DISCORD_USER_MAP: ${{ secrets.DISCORD_USER_MAP }}
