"""initial schema

Revision ID: 8e3e620b8509
Revises:
Create Date: 2026-08-20 19:34:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8e3e620b8509"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ("ext_conversations",)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversations",
        sa.Column(
            "team_id",
            sa.String(),
            nullable=True,
            comment="The ID of the related team",
        ),
        sa.Column(
            "user_id",
            sa.String(),
            nullable=True,
            comment="The ID of the related user",
        ),
        sa.Column("name", sa.String(), nullable=True, comment="The name"),
        sa.Column(
            "description",
            sa.String(),
            nullable=True,
            comment="Description of the conversation",
        ),
        sa.Column(
            "is_group_chat",
            sa.Boolean(),
            nullable=False,
            comment="Whether this conversation is a group chat",
        ),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("created_by_user_id", sa.String(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("updated_by_user_id", sa.String(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_by_user_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
        comment="Conversation table",
        info={
            "source_module": "extensions.conversations.BLL_Conversations",
            "extension": "conversations",
        },
    )
    op.create_table(
        "conversation_users",
        sa.Column(
            "conversation_id",
            sa.String(),
            nullable=False,
            comment="The ID of the related conversation",
        ),
        sa.Column(
            "user_id",
            sa.String(),
            nullable=False,
            comment="The ID of the related user",
        ),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("created_by_user_id", sa.String(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("updated_by_user_id", sa.String(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_by_user_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
        comment="ConversationUser table",
        info={
            "source_module": "extensions.conversations.BLL_Conversations",
            "extension": "conversations",
        },
    )
    op.create_table(
        "messages",
        sa.Column(
            "conversation_id",
            sa.String(),
            nullable=False,
            comment="The ID of the related conversation",
        ),
        sa.Column(
            "content", sa.String(), nullable=False, comment="Content of the message"
        ),
        sa.Column(
            "edited_at",
            sa.DateTime(),
            nullable=True,
            comment="When message was last edited",
        ),
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            nullable=False,
            comment="Whether message is soft deleted",
        ),
        sa.Column(
            "user_id",
            sa.String(),
            nullable=True,
            comment="ID of the user sending the message",
        ),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("created_by_user_id", sa.String(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("updated_by_user_id", sa.String(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_by_user_id", sa.String(), nullable=True),
        sa.Column(
            "parent_id",
            sa.String(),
            nullable=True,
            comment="The ID of the relevant parent",
        ),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"]),
        sa.ForeignKeyConstraint(["parent_id"], ["messages.id"]),
        sa.PrimaryKeyConstraint("id"),
        comment="Message table",
        info={
            "source_module": "extensions.conversations.BLL_Conversations",
            "extension": "conversations",
        },
    )
    op.create_table(
        "feedbacks",
        sa.Column(
            "message_id",
            sa.String(),
            nullable=True,
            comment="The ID of the related message",
        ),
        sa.Column(
            "user_id",
            sa.String(),
            nullable=True,
            comment="The ID of the related user",
        ),
        sa.Column("content", sa.String(), nullable=False, comment="Feedback content"),
        sa.Column(
            "positive",
            sa.Boolean(),
            nullable=True,
            comment="Whether this is positive (True), negative (False), or neutral (None) feedback",
        ),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("created_by_user_id", sa.String(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("updated_by_user_id", sa.String(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_by_user_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
        comment="Feedback table",
        info={
            "source_module": "extensions.conversations.BLL_Conversations",
            "extension": "conversations",
        },
    )
    op.create_table(
        "artifacts",
        sa.Column(
            "message_id",
            sa.String(),
            nullable=True,
            comment="The ID of the related message",
        ),
        sa.Column(
            "conversation_id",
            sa.String(),
            nullable=True,
            comment="The ID of the related conversation",
        ),
        sa.Column(
            "user_id",
            sa.String(),
            nullable=True,
            comment="The ID of the related user",
        ),
        sa.Column("name", sa.String(), nullable=True, comment="The name"),
        sa.Column(
            "relative_path",
            sa.String(),
            nullable=False,
            comment="Relative path to the artifact",
        ),
        sa.Column(
            "hosted_path",
            sa.String(),
            nullable=False,
            comment="Hosted path to the artifact",
        ),
        sa.Column(
            "content",
            sa.String(),
            nullable=True,
            comment="Embedded content of the artifact",
        ),
        sa.Column(
            "encrypted",
            sa.Boolean(),
            nullable=False,
            comment="Whether the artifact is encrypted",
        ),
        sa.Column(
            "file_size", sa.Integer(), nullable=True, comment="File size in bytes"
        ),
        sa.Column(
            "mime_type", sa.String(), nullable=True, comment="MIME type of the file"
        ),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("created_by_user_id", sa.String(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("updated_by_user_id", sa.String(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_by_user_id", sa.String(), nullable=True),
        sa.Column(
            "parent_id",
            sa.String(),
            nullable=True,
            comment="The ID of the relevant parent",
        ),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"]),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["parent_id"], ["artifacts.id"]),
        sa.PrimaryKeyConstraint("id"),
        comment="Artifact table",
        info={
            "source_module": "extensions.conversations.BLL_Conversations",
            "extension": "conversations",
        },
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("artifacts")
    op.drop_table("feedbacks")
    op.drop_table("messages")
    op.drop_table("conversation_users")
    op.drop_table("conversations")

    # ### end Alembic commands ###
